version: "3.7"
services:
  db:
    image: postgres
    container_name: db_app
    comamand: -p 5435
    expose:
      - 5435
    env_file:
      - .env-non-dev

  fastapi:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    ports:
      - 7331:8080
    depends_on:
      - db
      - redis